spring:
  application:
    name: news-hub
  profiles:
    include: SECRET-KEY
  datasource:
    url: ${mysql-url}
    username: ${mysql-username}
    password: ${mysql-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  jackson:
    property-naming-strategy: SNAKE_CASE
  web:
    cors:
      allowed-origin-patterns: "*"
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"
      allowed-credentials: true
springdoc:
  swagger-ui:
    path: /swagger
server:
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        same-site: none
        secure: true
        http-only: true
        domain: hyunewshub.shop
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: spring
    key-store-type: PKCS12
    key-alias: api.hyunewshub.shop
scheduler:
  use: true
  general-cron: 0 0 0/6 * * ?
  top-cron: 0 0 12 * * ?
